FROM mcr.microsoft.com/playwright/python:v1.60.0-jammy

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./
RUN pip install --no-cache-dir -r requirements-dev.txt

COPY receipts.py pytest.ini ./
COPY tests/ tests/

CMD ["pytest"]
